

export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOOGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REDUCE_ITEM_QTY: 'REDUCE_ITEM_QTY',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART'
}
